spring:
  profiles:
    include: social

  jackson.mapper.default-view-inclusion: true
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:file:~/bh-fantasy;AUTO_SERVER=TRUE
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jackson.serialization.fail-on-empty-beans: false

logging.level.org.hibernate:
  engine.internal.StatefulPersistenceContext: ERROR
  dialect.function.TemplateRenderer: ERROR
  #SQL: DEBUG

#spring.jpa.properties:
#  javax.persistence.schema-generation:
#    create-source: metadata
#    scripts:
#      action: update
#      create-target: update.sql
#  hibernate.hbm2ddl.delimiter: ;

server:
  use-forward-headers: true
  compression:
    enabled: true
    mime-types: text/css,text/javascript,application/javascript,application/x-font-ttf
  http2:
    enabled: true